# Generated by Django 5.2.12 on 2026-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_discharge_date_patient_is_discharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
