# Generated by Django 5.0.2 on 2026-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('ICU', 'ICU'), ('OT', 'Operation Theatre')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
