# Generated by Django 5.0.2 on 2026-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='average_consultation_time',
            field=models.IntegerField(default=15, help_text='Average time per patient in minutes'),
        ),
    ]
