# Generated by Django 5.2.12 on 2026-04-04 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctor_availability_status_and_more'),
        ('patients', '0002_patient_discharge_date_patient_is_discharged'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_reason', models.CharField(choices=[('Recovered', 'Recovered'), ('Transferred', 'Transferred to another facility'), ('Against Medical Advice', 'Against Medical Advice'), ('Deceased', 'Deceased'), ('Other', 'Other')], default='Recovered', max_length=50)),
                ('discharge_summary', models.TextField(blank=True, help_text="Medical summary of the patient's condition at discharge")),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Instructions for follow-up care')),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial Payment')], default='Pending', max_length=20)),
                ('discharged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges_performed', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='doctors.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='patients.patient')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='rooms.room')),
            ],
            options={
                'ordering': ['-discharge_date'],
            },
        ),
    ]
