# Generated by Django 5.2.12 on 2026-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('staff', 'Staff')], default='patient', max_length=20),
        ),
    ]
