# Generated by Django 5.0.2 on 2026-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Skipped', 'Skipped')], default='Waiting', max_length=20),
        ),
    ]
